/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "bskv_constants.h"

namespace bskv {

const bskvConstants g_bskv_constants;

bskvConstants::bskvConstants() {
}

} // namespace

