/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef bskv_CONSTANTS_H
#define bskv_CONSTANTS_H

#include "bskv_types.h"

namespace bskv {

class bskvConstants {
 public:
  bskvConstants();

};

extern const bskvConstants g_bskv_constants;

} // namespace

#endif
