/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "kv_constants.h"

namespace kv {

const kvConstants g_kv_constants;

kvConstants::kvConstants() {
}

} // namespace

