/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef kv_CONSTANTS_H
#define kv_CONSTANTS_H

#include "kv_types.h"

namespace kv {

class kvConstants {
 public:
  kvConstants();

};

extern const kvConstants g_kv_constants;

} // namespace

#endif
